### ISSUE TITLE
[v0.1] GitPeek crashes on page change

### ISSUE THREAD

**Issue by faurehu** [groupers/GitPeek#8]
Every time we follow an URL, GitPeek will stop working. Must reload for bringing GitPeek back to life.

**Comment by groupers** [comment]
Attempts:
<img width="711" alt="screen shot 2017-01-23 at 13 51 13" src="https://cloud.githubusercontent.com/assets/9064343/22206426/2331fe7e-e173-11e6-8c33-f77919aec970.png">

**Comment by phileasme** [comment]
**Attempts:**
_Attempt 1:_
Background.js :
```

var baseURL = 'about:blank'; // A default url just in case below code doesn't work
chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) { // onUpdated should 

chrome.tabs.sendMessage(tabId, {action: 'refresh_dialog', url: tab.url}, function(response) {});
baseURL = tab.url

/** Interesting fact:    Reacts on all change  **/
console.log(“URL has changed”);
});
```

main.js:
`chrome.extension.onMessage.addListener(function(msg, sender, sendResponse) {
//Will only react on the first change for some reason
  if (msg.action == 'refresh_dialog') {
}
});`


_Attempt 2:_
Breaks because there are too many reloads.
Background.js:
`chrome.runtime.reload();
chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
   chrome.tabs.executeScript(tabId, { file: "main.js" }, function() {});
}`

_Attempt 3:_
Do everything from contentscript put a variable listener on new constant:
constants.js
`var CURRENT_URL = { url : ‘’}`

Contentscript:
Apply watch on CURRENT_URL. 
`CURRENT_URL.watch( ‘url’, function (id,old, newval) {
// Reinitialise the clickListener 
});`
Fails. Because the page will enter a redirect loop calling document.location.href 
(Weirdest behaviour)
